"use client";
import {ChangeEvent,FormEvent,useEffect,useMemo,useRef,useState} from "react";

type Item={id:string;area:string;name:string;standard:string;kind?:"choice";options?:string[];hint?:string};
type Rec={id:string;inspection_date:string;shift:string;mode:string;operator_name:string;supervisor_name:string;status:string;abnormal_count:number;completed_count:number;total_count:number;responses_json:string;remarks:string;created_at:string};
const C=(id:string,area:string,name:string,standard="正常",options=["正常","異常"]):Item=>({id,area,name,standard,kind:"choice",options});
const N=(id:string,area:string,name:string,standard:string,hint="輸入現場／螢幕讀值"):Item=>({id,area,name,standard,hint});
const common:Item[]=[N("room_th","加速器室與 Pit","加速器室溫度／濕度","22–26 °C / <60%RH","例：25.5 °C / 40 %"),C("room_ac","加速器室與 Pit","加速器室空調狀態","ON",["ON","OFF"]),N("bt_th","加速器室與 Pit","BT 環境溫度／濕度","22–26 °C / <60%RH","例：23 °C / 47 %"),C("bt_ac","加速器室與 Pit","BT 區空調狀態","ON",["ON","OFF"]),C("water_leak","加速器室與 Pit","冷卻水歧管、接頭及地面漏水巡視","無漏水"),C("gas_leak","加速器室與 Pit","漏氣、異味或異常結霜巡視","無異常"),C("noise","加速器室與 Pit","異音及異常震動巡視","無異常"),N("power_th","電源供應室","電源室溫度／濕度","22–26 °C / <60%RH","例：24.9 °C / 52 %"),C("power_ac","電源供應室","電源室空調狀態","ON",["ON","OFF"]),C("power_leak","電源供應室","漏水巡視","無漏水"),C("pump_noise","冷卻水室","泵浦聲音及震動","無異音")];
const startup:Item[]=[C("network","加速器控制室","PLC 與 PC 網路狀態","ONLINE",["ONLINE","OFFLINE"]),N("coil","加速器控制室","Upper coil A / B / C / D 最高溫度","各組 <6.7 K","例：2.513 / 3.708 / 3.556 / 3.655 K"),N("lead","加速器控制室","Power lead P / N 最高溫度","各組 <65 K","例：44.553 / 44.329 K"),N("vacuum_a","加速器控制室","開機前真空壓力 (A)","<2.0E-4 Pa","例：1.9E-4"),N("vacuum_ba","加速器控制室","通水後壓差 (B-A)","<0.5E-5 Pa"),N("sector","加速器控制室","Sector 溫度","<33 °C"),N("filament","加速器控制室","Filament 電流／運轉時間",">90 A / <2000 min","例：100.39 A / 15215 min"),N("chimney","加速器控制室","Chimney Arc ON 運轉時間","min"),C("water_ready","加速器控制室","冷卻水狀態","Ready",["Ready","Not ready"]),C("purity","加速器控制室","水質警報","No alarm",["No alarm","Alarm"]),N("cryo_a","加速器控制室","Cryopump-A 二級／一級溫度","<20 / <85 K","例：9.7 / 70 K"),N("cryo_b","加速器控制室","Cryopump-B 二級／一級溫度","<20 / <85 K","例：9.7 / 73 K"),N("cryo_flow","加速器室與 Pit","Cryopump 水流量",">9 L/min"),N("cooler_flow","加速器室與 Pit","Cryocooler Comp A / B / C / D 水流量","各組 >9 L/min","例：9.7 / 9.6 / 9.6 / 9.6"),C("h2_open","加速器室與 Pit","氫氣瓶閥門","Open",["Open","異常"]),C("rf_reset","加速器室與 Pit","RF amp cabinet breaker 每日 OFF → ON","每日早晨執行",["已完成","異常"]),C("polarity","加速器室與 Pit","Filament current 極性／接線狀態","每班交換",["Straight","Cross","異常"]),C("door","加速器室與 Pit","室內無人且屏蔽門已關閉","已確認",["已確認","異常"]),C("air_open","冷卻水室","乾燥空氣瓶閥門","Open",["Open","異常"]),C("switch","電源供應室","受電開關","ON",["ON","OFF"]),C("cable","電源供應室","電纜外觀","無損傷")];
const shutdown:Item[]=[C("beam_record","加速器控制室","Ion chamber 使用紀錄已保存"),N("vacuum_gas","加速器控制室","有氣體時真空壓力","<2.0E-3 Pa"),N("coil_stop","加速器控制室","Upper coil A/B/C/D 最高溫度","<6.7 K"),N("lead_stop","加速器控制室","Power lead P/N 最高溫度","<65 K"),N("cryo_a_stop","加速器控制室","Cryopump-A 二級／一級溫度","<20 / <85 K"),N("cryo_b_stop","加速器控制室","Cryopump-B 二級／一級溫度","<20 / <85 K"),C("air_close","冷卻水室","乾燥空氣瓶閥門已關閉"),C("h2_close","加速器室與 Pit","氫氣瓶閥門已關閉")];

function Signature({label,value,onChange}:{label:string,value:string,onChange:(v:string)=>void}){const ref=useRef<HTMLCanvasElement>(null),drawing=useRef(false);function point(e:React.PointerEvent<HTMLCanvasElement>){const c=ref.current!,r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}function down(e:React.PointerEvent<HTMLCanvasElement>){drawing.current=true;const c=ref.current!,p=point(e),x=c.getContext("2d")!;x.beginPath();x.moveTo(p.x,p.y);c.setPointerCapture(e.pointerId)}function move(e:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;const c=ref.current!,p=point(e),x=c.getContext("2d")!;x.lineWidth=2.2;x.lineCap="round";x.strokeStyle="#17231f";x.lineTo(p.x,p.y);x.stroke()}function up(){drawing.current=false;onChange(ref.current!.toDataURL("image/png"))}function clear(){const c=ref.current!,x=c.getContext("2d")!;x.clearRect(0,0,c.width,c.height);onChange("")}return <label className="signature">{label}<canvas ref={ref} width="500" height="130" onPointerDown={down} onPointerMove={move} onPointerUp={up}/><button type="button" onClick={clear}>清除簽名</button>{value&&<span>✓ 已簽名</span>}</label>}

function paperMeta(x:Item){const control=x.area==="加速器控制室",cool=x.area==="冷卻水室",power=x.area==="電源供應室";let device=x.name.split(" ")[0],sub=control?"Beam Scheduler":cool?"Building":power?"Building / Power supply":"Accelerator / Building";if(x.name.includes("Cryopump"))device=x.name.includes("-A")?"Cryopump-A":x.name.includes("-B")?"Cryopump-B":"Cryopump";else if(x.name.includes("Cryocooler"))device="Cryocooler";else if(x.name.includes("真空"))device="Cyclotron vacuum chamber";else if(x.name.includes("空調")||x.name.includes("溫度／濕度"))device="Building";else if(x.name.includes("漏水"))device="Cooling water manifold";return{place:x.area,sub,device,unit:x.standard.match(/Pa|K|°C|L\/min|min|%RH/)?.[0]||"----",remark:x.id.includes("coil")?"Upper coil: A/B/C/D":x.id.includes("lead")?"Power lead: P/N":x.id.includes("ac")?"Air condition: ON or OFF":""}}

export default function Home(){
 const [screen,setScreen]=useState<"list"|"form"|"detail">("list"),[mode,setMode]=useState<"startup"|"shutdown">("startup"),[rows,setRows]=useState<Rec[]>([]),[chosen,setChosen]=useState<Rec|null>(null),[v,setV]=useState<Record<string,string>>({});
 const [meta,setMeta]=useState({date:new Date().toISOString().slice(0,10),time:new Date().toTimeString().slice(0,5),shift:"日班",operator1:"",operator2:"",signature1:"",signature2:"",supervisor:"",supervisorSignature:"",supervisorApproval:"待核可",remarks:""});
 const [ocr,setOcr]=useState("");
 const abnormalValues=new Set(["異常","OFFLINE","Not ready","Alarm","OFF"]);
 const items=useMemo(()=>[...(mode==="startup"?startup:shutdown),...common],[mode]), done=items.filter(x=>v[x.id]?.trim()).length, bad=Object.values(v).filter(x=>abnormalValues.has(x)).length;
 const load=()=>fetch("/api/inspections",{cache:"no-store"}).then(r=>r.json()).then(setRows); useEffect(()=>{load()},[]);
 const begin=(m:"startup"|"shutdown")=>{setMode(m);setV({});setScreen("form")};
 async function save(e:FormEvent,final:boolean){e.preventDefault();if(!meta.operator1.trim()||!meta.operator2.trim())return alert("請填寫兩位操作人員姓名");if(final&&(!meta.signature1||!meta.signature2))return alert("兩位操作人員都簽名後才能完成");if(final&&done<items.length)return alert("還有必填項目未完成");const approved=meta.supervisorApproval==="已核可"&&!!meta.supervisor&&!!meta.supervisorSignature;const r=await fetch("/api/inspections",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({date:meta.date,shift:meta.shift,operator:`${meta.operator1} / ${meta.operator2}`,supervisor:meta.supervisor,remarks:meta.remarks,mode,status:final?(approved?"completed":"awaiting_supervisor"):"draft",responses:{...v,_inspection_time:final?new Date().toTimeString().slice(0,5):meta.time,_operator1:meta.operator1,_operator2:meta.operator2,_signature1:meta.signature1,_signature2:meta.signature2,_supervisor_signature:meta.supervisorSignature,_supervisor_approval:meta.supervisorApproval},abnormalCount:bad,completedCount:done,totalCount:items.length})});if(!r.ok)return alert("儲存失敗");await load();setScreen("list")}
 async function recognize(e:ChangeEvent<HTMLInputElement>,id:string){const file=e.target.files?.[0];if(!file)return;setOcr("辨識中，首次使用約需數十秒…");try{const {recognize}=await import("tesseract.js");const result=await recognize(file,"eng",{logger:m=>m.status&&setOcr(`${m.status} ${Math.round((m.progress||0)*100)}%`)});const nums=result.data.text.match(/-?\d+(?:\.\d+)?/g)||[];setV(old=>({...old,[id]:nums.length>=2?`${nums[0]} °C / ${nums[1]} %`:result.data.text.trim()}));setOcr("辨識完成，請人工核對數值")}catch{setOcr("辨識失敗，請重新拍攝或手動輸入")}}
 function exportExcel(){const head=["紀錄編號","日期","時間","班別","類型","操作員1","操作員2","主管","主管核可","區域","檢查項目","標準值","結果","異常","備註","建立時間"],lines=[head];for(const r of rows){const data=JSON.parse(r.responses_json||"{}"),list=[...(r.mode==="startup"?startup:shutdown),...common];for(const x of list)lines.push([r.id,r.inspection_date,data._inspection_time||"",r.shift,r.mode==="startup"?"開機":"關機",data._operator1||r.operator_name,data._operator2||"",r.supervisor_name,data._supervisor_approval||"",x.area,x.name,x.standard,data[x.id]||"",abnormalValues.has(data[x.id])?"是":"否",r.remarks,r.created_at])}const csv="\uFEFF"+lines.map(a=>a.map(z=>`"${String(z??"").replaceAll('"','""')}"`).join(",")).join("\r\n"),u=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=u;a.download=`加速器巡檢分析_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(u)}
 const groups=items.reduce<Record<string,Item[]>>((a,x)=>{(a[x.area]??=[]).push(x);return a},{});
 return <main><header><div className="brand"><b>A</b><span><strong>加速器每日巡檢</strong><small>數位紀錄系統</small></span></div><nav><button onClick={()=>setScreen("list")}>紀錄總覽</button><button onClick={()=>begin("startup")}>新增開機</button><button onClick={()=>begin("shutdown")}>新增關機</button></nav></header>
 {screen==="list"&&<div className="page"><section className="hero"><div><em>DAILY OPERATIONS</em><h1>每日巡檢，一目了然</h1><p>雙人簽名、主管核可、異常追蹤與參數分析。</p></div><div><button onClick={exportExcel}>匯出 Excel 分析檔</button><button className="primary" onClick={()=>begin("startup")}>＋ 開機巡檢</button><button onClick={()=>begin("shutdown")}>＋ 關機巡檢</button></div></section><section className="cards"><article><small>紀錄總數</small><b>{rows.length}</b></article><article><small>待完成</small><b>{rows.filter(x=>x.status!=="completed").length}</b></article><article><small>異常項目</small><b>{rows.reduce((a,x)=>a+x.abnormal_count,0)}</b></article></section><section className="panel"><div className="panelTitle"><h2>巡檢紀錄</h2><button onClick={load}>重新整理</button></div><div className="scroll"><table><thead><tr><th>日期</th><th>班別</th><th>類型</th><th>兩位操作員</th><th>完成度</th><th>異常</th><th>狀態</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id} onClick={()=>{setChosen(r);setScreen("detail")}}><td>{r.inspection_date}</td><td>{r.shift}</td><td><i>{r.mode==="startup"?"開機":"關機"}</i></td><td>{r.operator_name}</td><td>{r.completed_count}/{r.total_count}</td><td className="danger">{r.abnormal_count||"—"}</td><td><i className={r.status}>{r.status==="completed"?"主管已核可":r.status==="awaiting_supervisor"?"待主管核可":"草稿"}</i></td></tr>):<tr><td colSpan={7} className="empty">尚無紀錄，請建立第一筆巡檢。</td></tr>}</tbody></table></div></section></div>}
 {screen==="form"&&<form className="page" onSubmit={e=>save(e,false)}><div className="title"><div><button type="button" onClick={()=>setScreen("list")}>← 返回</button><em>{mode.toUpperCase()}</em><h1>每日{mode==="startup"?"開機":"關機"}巡檢</h1></div><div className="count"><b>{done}/{items.length}</b><small>已填寫</small></div></div><section className="meta"><label>日期<input type="date" value={meta.date} onChange={e=>setMeta({...meta,date:e.target.value})}/></label><label>完成時間（送出時自動更新）<input type="time" value={meta.time} readOnly/></label><label>班別<select value={meta.shift} onChange={e=>setMeta({...meta,shift:e.target.value})}><option>日班</option><option>小夜班</option><option>大夜班</option></select></label><label>操作員 1 *<input value={meta.operator1} onChange={e=>setMeta({...meta,operator1:e.target.value})}/></label><label>操作員 2 *<input value={meta.operator2} onChange={e=>setMeta({...meta,operator2:e.target.value})}/></label></section>{Object.entries(groups).map(([area,xs],n)=><section className="group" key={area}><h2><span>{n+1}</span>{area}<small>{xs.length} 項</small></h2>{xs.map(x=><div className="check" key={x.id}><div><strong>{x.name}</strong><small>標準：{x.standard}</small>{(x.id==="room_th"||x.id==="power_th")&&<label className="ocr">拍攝／選擇顯示器照片<input type="file" accept="image/*" capture="environment" onChange={e=>recognize(e,x.id)}/></label>}</div>{x.kind==="choice"?<div className="buttons">{x.options!.map(o=><button key={o} type="button" className={v[x.id]===o?(abnormalValues.has(o)?"no":"yes"):""} onClick={()=>setV({...v,[x.id]:o})}>{o}</button>)}</div>:<input value={v[x.id]||""} onChange={e=>setV({...v,[x.id]:e.target.value})} placeholder={x.hint||"輸入現場／螢幕讀值"}/>}</div>)}</section>)}{ocr&&<p className="ocrStatus">{ocr}</p>}<section className="signatures"><Signature label="操作員 1 簽名" value={meta.signature1} onChange={x=>setMeta({...meta,signature1:x})}/><Signature label="操作員 2 簽名" value={meta.signature2} onChange={x=>setMeta({...meta,signature2:x})}/><div className="approval"><label>主管姓名<input value={meta.supervisor} onChange={e=>setMeta({...meta,supervisor:e.target.value})}/></label><label>主管核可<select value={meta.supervisorApproval} onChange={e=>setMeta({...meta,supervisorApproval:e.target.value})}><option>待核可</option><option>已核可</option><option>退回修正</option></select></label><Signature label="主管簽名" value={meta.supervisorSignature} onChange={x=>setMeta({...meta,supervisorSignature:x})}/></div></section><section className="notes"><label>備註與異常處置<textarea value={meta.remarks} onChange={e=>setMeta({...meta,remarks:e.target.value})}/></label></section><div className="actions"><span className={bad?"danger":""}>{bad?`⚠ ${bad} 項異常，請填寫處置說明`:"完成時會自動記錄時間；兩位操作員皆須簽名"}</span><button type="submit">儲存草稿</button><button type="button" className="primary" onClick={e=>save(e as unknown as FormEvent,true)}>雙人簽名後送出</button></div></form>}
 {screen==="detail"&&chosen&&<div className="page"><div className="printbar"><button onClick={()=>setScreen("list")}>← 返回</button><button className="primary" onClick={()=>print()}>列印／另存 PDF</button></div><article className="report paperReport">{(()=>{const d=JSON.parse(chosen.responses_json||"{}");return <><div className="paperTop"><b>{chosen.mode==="startup"?"Startup":"Shutdown"}</b><span>Rev.03</span></div><table className="paperTable"><thead><tr><th>Place</th><th>Sub system</th><th>Device</th><th>Check items</th><th>(Unit)</th><th>Standard value</th><th>Check</th><th>Remark</th></tr></thead><tbody>{[...(chosen.mode==="startup"?startup:shutdown),...common].map(x=>{const z=d[x.id]||"—",m=paperMeta(x);return <tr key={x.id} className={abnormalValues.has(z)?"abnormal":""}><td>{m.place}</td><td>{m.sub}</td><td>{m.device}</td><td>{x.name}</td><td>{m.unit}</td><td>{x.standard}</td><td><b>{z}</b></td><td>{m.remark}</td></tr>})}</tbody></table><div className="paperSign"><b>Daily {chosen.mode==="startup"?"Startup":"Shutdown"} Sheet</b><span>Supervisor: {chosen.supervisor_name||"________"}</span><span>Date: {chosen.inspection_date}</span><span>Time: {d._inspection_time||"—"}</span><span>Operator 1: {d._operator1||"—"}</span><span>Operator 2: {d._operator2||"—"}</span></div><div className="signaturePrint">{d._signature1&&<figure><img src={d._signature1} alt="操作員1簽名"/><figcaption>操作員1簽名</figcaption></figure>}{d._signature2&&<figure><img src={d._signature2} alt="操作員2簽名"/><figcaption>操作員2簽名</figcaption></figure>}{d._supervisor_signature&&<figure><img src={d._supervisor_signature} alt="主管簽名"/><figcaption>主管簽名 · {d._supervisor_approval}</figcaption></figure>}</div><div className="reportNotes"><small>Remark / 異常處置</small><p>{chosen.remarks||"無"}</p></div><footer>紀錄編號：{chosen.id}　建立時間：{new Date(chosen.created_at).toLocaleString("zh-TW")}</footer></>})()}</article></div>}</main>}
