"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";

type Item={id:string;area:string;name:string;standard:string;kind?:"choice"};
type Rec={id:string;inspection_date:string;shift:string;mode:string;operator_name:string;supervisor_name:string;status:string;abnormal_count:number;completed_count:number;total_count:number;responses_json:string;remarks:string;created_at:string};
const C=(id:string,area:string,name:string,standard="正常"):Item=>({id,area,name,standard,kind:"choice"});
const N=(id:string,area:string,name:string,standard:string):Item=>({id,area,name,standard});
const common:Item[]=[N("room_th","加速器室與 Pit","加速器室溫度／濕度","22–26 °C / <60%RH"),N("bt_th","加速器室與 Pit","BT 環境溫度／濕度","22–26 °C / <60%RH"),C("water_leak","加速器室與 Pit","管路、接頭及地面漏水巡視","無漏水"),C("gas_leak","加速器室與 Pit","漏氣、異味或異常結霜巡視","無異常"),C("noise","加速器室與 Pit","異音及異常震動巡視","無異常"),N("power_th","電源供應室","電源室溫度／濕度","22–26 °C / <60%RH"),C("power_leak","電源供應室","漏水巡視","無漏水"),C("pump_noise","冷卻水室","泵浦聲音及震動","無異音")];
const startup:Item[]=[C("network","加速器控制室","PLC 與 PC 網路狀態","ONLINE"),N("coil","加速器控制室","Upper coil A/B/C/D 最高溫度","<6.7 K"),N("lead","加速器控制室","Power lead P/N 最高溫度","<65 K"),N("vacuum_a","加速器控制室","開機前真空壓力 (A)","<2.0E-4 Pa"),N("vacuum_ba","加速器控制室","通水後壓差 (B-A)","<0.5E-5 Pa"),N("sector","加速器控制室","Sector 溫度","<33 °C"),N("filament","加速器控制室","Filament 電流／運轉時間",">90 A / <2000 min"),N("chimney","加速器控制室","Chimney Arc ON 運轉時間","min"),C("water_ready","加速器控制室","冷卻水狀態","Ready"),C("purity","加速器控制室","水質警報","無警報"),N("cryo_a","加速器控制室","Cryopump-A 二級／一級溫度","<20 / <85 K"),N("cryo_b","加速器控制室","Cryopump-B 二級／一級溫度","<20 / <85 K"),N("cryo_flow","加速器室與 Pit","Cryopump 水流量",">9 L/min"),N("cooler_flow","加速器室與 Pit","Cryocooler Comp A/B/C/D 水流量",">9 L/min"),C("h2_open","加速器室與 Pit","氫氣瓶閥門已開啟"),C("polarity","加速器室與 Pit","Filament current 極性交換已完成"),C("door","加速器室與 Pit","室內無人且屏蔽門已關閉"),C("air_open","冷卻水室","乾燥空氣瓶閥門已開啟"),C("switch","電源供應室","受電開關為 ON"),C("cable","電源供應室","電纜外觀無損傷")];
const shutdown:Item[]=[C("beam_record","加速器控制室","Ion chamber 使用紀錄已保存"),N("vacuum_gas","加速器控制室","有氣體時真空壓力","<2.0E-3 Pa"),N("coil_stop","加速器控制室","Upper coil A/B/C/D 最高溫度","<6.7 K"),N("lead_stop","加速器控制室","Power lead P/N 最高溫度","<65 K"),N("cryo_a_stop","加速器控制室","Cryopump-A 二級／一級溫度","<20 / <85 K"),N("cryo_b_stop","加速器控制室","Cryopump-B 二級／一級溫度","<20 / <85 K"),C("air_close","冷卻水室","乾燥空氣瓶閥門已關閉"),C("h2_close","加速器室與 Pit","氫氣瓶閥門已關閉")];

export default function Home(){
 const [screen,setScreen]=useState<"list"|"form"|"detail">("list"),[mode,setMode]=useState<"startup"|"shutdown">("startup"),[rows,setRows]=useState<Rec[]>([]),[chosen,setChosen]=useState<Rec|null>(null),[v,setV]=useState<Record<string,string>>({});
 const [meta,setMeta]=useState({date:new Date().toISOString().slice(0,10),shift:"日班",operator:"",supervisor:"",remarks:""});
 const items=useMemo(()=>[...(mode==="startup"?startup:shutdown),...common],[mode]), done=items.filter(x=>v[x.id]?.trim()).length, bad=Object.values(v).filter(x=>x==="異常").length;
 const load=()=>fetch("/api/inspections",{cache:"no-store"}).then(r=>r.json()).then(setRows); useEffect(()=>{load()},[]);
 const begin=(m:"startup"|"shutdown")=>{setMode(m);setV({});setScreen("form")};
 async function save(e:FormEvent,final:boolean){e.preventDefault();if(!meta.operator.trim())return alert("請填操作員姓名");if(final&&done<items.length)return alert("還有必填項目未完成");const r=await fetch("/api/inspections",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...meta,mode,status:final?"completed":"draft",responses:v,abnormalCount:bad,completedCount:done,totalCount:items.length})});if(!r.ok)return alert("儲存失敗");await load();setScreen("list")}
 const groups=items.reduce<Record<string,Item[]>>((a,x)=>{(a[x.area]??=[]).push(x);return a},{});
 return <main><header><div className="brand"><b>A</b><span><strong>加速器每日巡檢</strong><small>數位紀錄系統</small></span></div><nav><button onClick={()=>setScreen("list")}>紀錄總覽</button><button onClick={()=>begin("startup")}>新增開機</button><button onClick={()=>begin("shutdown")}>新增關機</button></nav></header>
 {screen==="list"&&<div className="page"><section className="hero"><div><em>DAILY OPERATIONS</em><h1>每日巡檢，一目了然</h1><p>多人登錄、異常追蹤與紙本歸檔。</p></div><div><button className="primary" onClick={()=>begin("startup")}>＋ 開機巡檢</button><button onClick={()=>begin("shutdown")}>＋ 關機巡檢</button></div></section><section className="cards"><article><small>紀錄總數</small><b>{rows.length}</b></article><article><small>待完成</small><b>{rows.filter(x=>x.status!=="completed").length}</b></article><article><small>異常項目</small><b>{rows.reduce((a,x)=>a+x.abnormal_count,0)}</b></article></section><section className="panel"><div className="panelTitle"><h2>巡檢紀錄</h2><button onClick={load}>重新整理</button></div><div className="scroll"><table><thead><tr><th>日期</th><th>班別</th><th>類型</th><th>操作員</th><th>完成度</th><th>異常</th><th>狀態</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id} onClick={()=>{setChosen(r);setScreen("detail")}}><td>{r.inspection_date}</td><td>{r.shift}</td><td><i>{r.mode==="startup"?"開機":"關機"}</i></td><td>{r.operator_name}</td><td>{r.completed_count}/{r.total_count}</td><td className="danger">{r.abnormal_count||"—"}</td><td><i className={r.status}>{r.status==="completed"?"已完成":"草稿"}</i></td></tr>):<tr><td colSpan={7} className="empty">尚無紀錄，請建立第一筆巡檢。</td></tr>}</tbody></table></div></section></div>}
 {screen==="form"&&<form className="page" onSubmit={e=>save(e,false)}><div className="title"><div><button type="button" onClick={()=>setScreen("list")}>← 返回</button><em>{mode.toUpperCase()}</em><h1>每日{mode==="startup"?"開機":"關機"}巡檢</h1></div><div className="count"><b>{done}/{items.length}</b><small>已填寫</small></div></div><section className="meta"><label>日期<input type="date" value={meta.date} onChange={e=>setMeta({...meta,date:e.target.value})}/></label><label>班別<select value={meta.shift} onChange={e=>setMeta({...meta,shift:e.target.value})}><option>日班</option><option>小夜班</option><option>大夜班</option></select></label><label>操作員 *<input value={meta.operator} onChange={e=>setMeta({...meta,operator:e.target.value})}/></label><label>主管<input value={meta.supervisor} onChange={e=>setMeta({...meta,supervisor:e.target.value})}/></label></section>{Object.entries(groups).map(([area,xs],n)=><section className="group" key={area}><h2><span>{n+1}</span>{area}<small>{xs.length} 項</small></h2>{xs.map(x=><div className="check" key={x.id}><div><strong>{x.name}</strong><small>標準：{x.standard}</small></div>{x.kind==="choice"?<div className="buttons"><button type="button" className={v[x.id]==="正常"?"yes":""} onClick={()=>setV({...v,[x.id]:"正常"})}>正常／已確認</button><button type="button" className={v[x.id]==="異常"?"no":""} onClick={()=>setV({...v,[x.id]:"異常"})}>異常</button></div>:<input value={v[x.id]||""} onChange={e=>setV({...v,[x.id]:e.target.value})} placeholder="輸入現場／螢幕讀值"/>}</div>)}</section>)}<section className="notes"><label>備註與異常處置<textarea value={meta.remarks} onChange={e=>setMeta({...meta,remarks:e.target.value})}/></label></section><div className="actions"><span className={bad?"danger":""}>{bad?`⚠ ${bad} 項異常，請填寫處置說明`:"資料將保留填寫者與時間"}</span><button type="submit">儲存草稿</button><button type="button" className="primary" onClick={e=>save(e as unknown as FormEvent,true)}>完成並簽核</button></div></form>}
 {screen==="detail"&&chosen&&<div className="page"><div className="printbar"><button onClick={()=>setScreen("list")}>← 返回</button><button className="primary" onClick={()=>print()}>列印／另存 PDF</button></div><article className="report"><div className="reportTitle"><div><em>DAILY INSPECTION REPORT</em><h1>加速器每日{chosen.mode==="startup"?"開機":"關機"}巡檢紀錄</h1></div><i className={chosen.status}>{chosen.status==="completed"?"已完成":"草稿"}</i></div><div className="reportMeta"><span>日期<b>{chosen.inspection_date}</b></span><span>班別<b>{chosen.shift}</b></span><span>操作員<b>{chosen.operator_name}</b></span><span>主管<b>{chosen.supervisor_name||"—"}</b></span></div><table><thead><tr><th>區域</th><th>檢查項目</th><th>標準</th><th>結果</th></tr></thead><tbody>{[...(chosen.mode==="startup"?startup:shutdown),...common].map(x=>{const z=JSON.parse(chosen.responses_json)[x.id]||"—";return <tr key={x.id} className={z==="異常"?"abnormal":""}><td>{x.area}</td><td>{x.name}</td><td>{x.standard}</td><td><b>{z}</b></td></tr>})}</tbody></table><div className="reportNotes"><small>備註／異常處置</small><p>{chosen.remarks||"無"}</p></div><footer>紀錄編號：{chosen.id}　建立時間：{new Date(chosen.created_at).toLocaleString("zh-TW")}</footer></article></div>}</main>}
